export const dashboard_data = [
    {
        //key : //value
        course : "ITPC 11 BSIT 3-1",
        courseTitle : "Information Management 2",
        description : "Description Placeholder",
        totalStudents : "31 Students",
        courseImage : "assets/images/ITPC11.jpg",
        studentImage1 : "assets/images/samplestudent1.jpg",
        studentImage2 : "assets/images/samplestudent2.jpg",
    },
    {
        course : "ITPC 11 BSIT 3-2",
        courseTitle : "Information Management 2",
        description : "Description Placeholder",
        totalStudents : "28 Students",
        courseImage : "assets/images/ITPC11.jpg",
        studentImage1 : "assets/images/samplestudent3.jpg",
        studentImage2 : "assets/images/samplestudent4.jpg",
    },
    {
        course : "ITPC 12 BSIT 3-1",
        courseTitle : "Data Communication and Networking 1",
        description : "Description Placeholder",
        totalStudents : "32 Students",
        courseImage : "assets/images/ITPC12.jpg",
        studentImage1 : "assets/images/samplestudent2.jpg",
        studentImage2 : "assets/images/samplestudent1.jpg",
    },
    {
        course : "ITPC 12 BSIT 3-2",
        courseTitle : "Data Communication and Networking 1",
        description : "Description Placeholder",
        totalStudents : "29 Students",
        courseImage : "assets/images/ITPC12.jpg",
        studentImage1 : "assets/images/samplestudent4.jpg",
        studentImage2 : "assets/images/samplestudent3.jpg",
    },
    {
        course : "ITPE 1 BSIT 3-1",
        courseTitle : "IT Professional Elective 1",
        description : "Description Placeholder",
        totalStudents : "31 Students",
        courseImage : "assets/images/ITPE1.jpg",
        studentImage1 : "assets/images/samplestudent1.jpg",
        studentImage2 : "assets/images/samplestudent3.jpg",
    },
    {
        course : "ITPE 1 BSIT 3-2",
        courseTitle : "IT Professional Elective 1",
        description : "Description Placeholder",
        totalStudents : "29 Students",
        courseImage : "assets/images/ITPE1.jpg",
        studentImage1 : "assets/images/samplestudent2.jpg",
        studentImage2 : "assets/images/samplestudent4.jpg",
    },
    {
        course : "ITPE 2 BSIT 3-1",
        courseTitle : "IT Professional Elective 2",
        description : "Description Placeholder",
        totalStudents : "34 Students",
        courseImage : "assets/images/ITPE2.jpg",
        studentImage1 : "assets/images/samplestudent4.jpg",
        studentImage2 : "assets/images/samplestudent1.jpg",
    },
    {
        course : "ITPE 2 BSIT 3-2",
        courseTitle : "IT Professional Elective 2",
        description : "Description Placeholder",
        totalStudents : "30 Students",
        courseImage : "assets/images/ITPE2.jpg",
        studentImage1 : "assets/images/samplestudent3.jpg",
        studentImage2 : "assets/images/samplestudent1.jpg",
    },
    {
        course : "ITPC 13 BSIT 3-1",
        courseTitle : "System Analysis and Design",
        description : "Description Placeholder",
        totalStudents : "31 Students",
        courseImage : "assets/images/ITPC13.jpg",
        studentImage1 : "assets/images/samplestudent4.jpg",
        studentImage2 : "assets/images/samplestudent2.jpg",
    },
    {
        course : "ITPC 14 BSIT 3-2",
        courseTitle : "Intro to Digitial Logic Design & Consumer Electronics",
        description : "Description Placeholder",
        totalStudents : "28 Students",
        courseImage : "assets/images/ITPC14.jpg",
        studentImage1 : "assets/images/samplestudent2.jpg",
        studentImage2 : "assets/images/samplestudent3.jpg",
    },
    {
        course : "ITPC 15 BSIT 3-1",
        courseTitle : "System Analysis and Design",
        description : "Description Placeholder",
        totalStudents : "31 Students",
        courseImage : "assets/images/ITPC15.jpg",
        studentImage1 : "assets/images/samplestudent3.jpg",
        studentImage2 : "assets/images/samplestudent1.jpg",
    },
    
    
    
]