export const students_data = [
    {
        course : "ITPC 11",
        section : "BSIT 3-1",
        row1StudentImage : "assets/images/samplestudent1.jpg",
        row1Name : "Veronica C. Madrigal",
        row1Email : "sampleemail1@gmail.com",
        row1ID : "2134985",
        row1Grades : "#",
        row2StudentImage : "assets/images/samplestudent2.jpg",
        row2Name : "Olaf G. Mensir",
        row2Email : "sampleemail2@gmail.com",
        row2ID : "5028492",
        row2Grades : "#",
        row3StudentImage : "assets/images/samplestudent3.jpg",
        row3Name : "Drake G. Delos Reyes",
        row3Email : "sampleemail3@gmail.com",
        row3ID : "21735293",
        row3Grades : "#",
        row4StudentImage : "assets/images/samplestudent4.jpg",
        row4Name : "Mary Jane. F. Gonzales",
        row4Email : "sampleemail4@gmail.com",
        row4ID : "9251925",
        row4Grades : "#",
    },
    {
        course : "ITPC 12",
        section : "BSIT 3-1",
        row1StudentImage : "assets/images/samplestudent1.jpg",
        row1Name : "Vinny C. Madrigal",
        row1Email : "sampleemail5@gmail.com",
        row1ID : "1839848",
        row1Grades : "#",
        row2StudentImage : "assets/images/samplestudent2.jpg",
        row2Name : "Korad F. Valen",
        row2Email : "sampleemail6@gmail.com",
        row2ID : "7281927",
        row2Grades : "#",
        row3StudentImage : "assets/images/samplestudent3.jpg",
        row3Name : "Drake G. Delos Reyes",
        row3Email : "sampleemail3@gmail.com",
        row3ID : "21735293",
        row3Grades : "#",
        row4StudentImage : "assets/images/samplestudent4.jpg",
        row4Name : "Mary Jane. F. Gonzales",
        row4Email : "sampleemail4@gmail.com",
        row4ID : "9251925",
        row4Grades : "#",
    }
]