export const teachers_data = [
    {
        course : "ITPC 11 - Information Management 2",
        name : "Thomas J. Peterson",
        description : "Description Placeholder",
        imageTeacher : "assets/images/sampleteacher1.jpg",
        section1 : "BSIT 1-1",
        section2 : "BSIT 1-2",
        section3 : "BSIT 3-1",
        section4 : "BSIT 2-1",
    },
    {
        course : "ITPC 12 - Data Communication and Networking 1",
        name : "Katherine C. Desmanos",
        description : "Description Placeholder",
        imageTeacher : "assets/images/sampleteacher2.jpg",
        section1 : "BSIT 2-1",
        section2 : "BSIT 2-2",
        section3 : "BSIT 3-1",
        section4 : "BSIT 3-2",
    },
    {
        course : "ITPC 13 - System Analysis and Design",
        name : "Ark O. Pernavidad",
        description : "Description Placeholder",
        imageTeacher : "assets/images/sampleteacher3.jpg",
        section1 : "BSIT 1-1",
        section2 : "BSIT 2-1",
        section3 : "BSIT 3-1",
        section4 : "BSIT 3-2",
    },
]